services:
  fastapi-service:
    image: elvispro1993/afroverseas-backend:latest
    container_name: afroverseas_app
    restart: always
    # Matches your project structure
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # PERSISTENCE: This ensures videos/CVs survive the GitHub Action update
      - ./static/uploads:/app/static/uploads
      - ./index.html:/app/index.html
    depends_on:
      - fastapi-db
    networks:
      - afroverseas_net

  fastapi-db:
    image: postgres:15-alpine
    container_name: afroverseas_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - afroverseas_net

volumes:
  postgres_prod_data:

networks:
  afroverseas_net:
    driver: bridge